const approvalHistoryData = [
    {
        "Message": "9 Actions Performed on this Document.",
        "HaveApprovalHistory": true,
        "Data": [
            {
                "CategoryName": "Purchase Order (PO)",
                "DocumentNo": "6400001791",
                "FinalStatus": "Return Level 1",
                "ApproverLevel": "-2",
                "ApproverEmpcode": "23097",
                "ApproverName": "Naveen Vashishtha",
                "ApproverDecisionStatus": "APPROVED",
                "ApproverRemarks": "REPEAT PO ",
                "ApproverActionDate": "24-02-2024 17:02:00",
                "ApproverDesignation": "Deputy Manager",
                "ApproverMail": "naveen.vashishtha@sonalika.com",
                "ApproverContact": "9115527970",
                "ApproverDept": "P&M"
            },
            {
                "CategoryName": "Purchase Order (PO)",
                "DocumentNo": "6400001791",
                "FinalStatus": "Return Level 1",
                "ApproverLevel": "-1",
                "ApproverEmpcode": "28094",
                "ApproverName": "Nitin Dahiya",
                "ApproverDecisionStatus": "APPROVED",
                "ApproverRemarks": "Indent based PO as per SAP feeded repeat rates",
                "ApproverActionDate": "27-02-2024 08:32:00",
                "ApproverDesignation": "Chief Manager",
                "ApproverMail": "nitin.dahiya@sonalika.com",
                "ApproverContact": "9115509365",
                "ApproverDept": "P&M"
            },
            {
                "CategoryName": "Purchase Order (PO)",
                "DocumentNo": "6400001791",
                "FinalStatus": "Return Level 1",
                "ApproverLevel": "0",
                "ApproverEmpcode": "30661",
                "ApproverName": "Virag Bhardwaj",
                "ApproverDecisionStatus": "APPROVED",
                "ApproverRemarks": "Approved, repeat order ",
                "ApproverActionDate": "27-02-2024 20:56:00",
                "ApproverDesignation": "Deputy General Manager",
                "ApproverMail": "",
                "ApproverContact": "7341105940",
                "ApproverDept": "P&M"
            },
            {
                "CategoryName": "Purchase Order (PO)",
                "DocumentNo": "6400001791",
                "FinalStatus": "Return Level 1",
                "ApproverLevel": "1",
                "ApproverEmpcode": "28996",
                "ApproverName": "Puneet Garg",
                "ApproverDecisionStatus": "RETURN",
                "ApproverRemarks": "Please Check DOA Condition",
                "ApproverActionDate": "28-02-2024 09:23:00",
                "ApproverDesignation": "General Manager",
                "ApproverMail": "Puneet.Garg@sonalika.com",
                "ApproverContact": "8130837773",
                "ApproverDept": "Purchase-Noida"
            },
            {
                "CategoryName": "Purchase Order (PO)",
                "DocumentNo": "6400001791",
                "FinalStatus": "PENDING",
                "ApproverLevel": "-3",
                "ApproverEmpcode": "23097",
                "ApproverName": "Naveen Vashishtha",
                "ApproverDecisionStatus": "APPROVED",
                "ApproverRemarks": "REPEAT PO ",
                "ApproverActionDate": "28-02-2024 11:21:00",
                "ApproverDesignation": "Deputy Manager",
                "ApproverMail": "naveen.vashishtha@sonalika.com",
                "ApproverContact": "9115527970",
                "ApproverDept": "P&M"
            },
            {
                "CategoryName": "Purchase Order (PO)",
                "DocumentNo": "6400001791",
                "FinalStatus": "PENDING",
                "ApproverLevel": "-2",
                "ApproverEmpcode": "28094",
                "ApproverName": "Nitin Dahiya",
                "ApproverDecisionStatus": "APPROVED",
                "ApproverRemarks": "Indent based PO as per SAP feeded repeat rates",
                "ApproverActionDate": "01-03-2024 11:25:00",
                "ApproverDesignation": "Chief Manager",
                "ApproverMail": "nitin.dahiya@sonalika.com",
                "ApproverContact": "9115509365",
                "ApproverDept": "P&M"
            },
            {
                "CategoryName": "Purchase Order (PO)",
                "DocumentNo": "6400001791",
                "FinalStatus": "PENDING",
                "ApproverLevel": "-1",
                "ApproverEmpcode": "30661",
                "ApproverName": "Virag Bhardwaj",
                "ApproverDecisionStatus": "APPROVED",
                "ApproverRemarks": "Approved as per rate Info 2021 & 2022",
                "ApproverActionDate": "02-03-2024 15:38:00",
                "ApproverDesignation": "Deputy General Manager",
                "ApproverMail": "",
                "ApproverContact": "7341105940",
                "ApproverDept": "P&M"
            },
            {
                "CategoryName": "Purchase Order (PO)",
                "DocumentNo": "6400001791",
                "FinalStatus": "PENDING",
                "ApproverLevel": "0",
                "ApproverEmpcode": "28996",
                "ApproverName": "Puneet Garg",
                "ApproverDecisionStatus": "APPROVED",
                "ApproverRemarks": "Repeat Prices",
                "ApproverActionDate": "02-03-2024 15:45:00",
                "ApproverDesignation": "General Manager",
                "ApproverMail": "Puneet.Garg@sonalika.com",
                "ApproverContact": "8130837773",
                "ApproverDept": "Purchase-Noida"
            },
            {
                "CategoryName": "Purchase Order (PO)",
                "DocumentNo": "6400001791",
                "FinalStatus": "PENDING",
                "ApproverLevel": "1",
                "ApproverEmpcode": "28167",
                "ApproverName": "Rohit Kalia",
                "ApproverDecisionStatus": "PENDING",
                "ApproverRemarks": "",
                "ApproverActionDate": "",
                "ApproverDesignation": "President & Chief-Surc&ME",
                "ApproverMail": "Rohit.Kalia@sonalika.com",
                "ApproverContact": "9501004863",
                "ApproverDept": "Purchase-Noida"
            }
        ]
    }
];

export default approvalHistoryData;
